packages:
  - apps/*
  - packages/*

catalogs:
  better-auth:
    better-auth: ^1.3.29
  chess:
    chess.js: ^1.4.0
  dotenv:
    dotenv: ^17.2.3
  next:
    next: ^16.0.10
  prisma:
    "@prisma/client": ^7.0.0
    prisma: 7.0.0
  trpc:
    "@trpc/client": ^11.6.0
    "@trpc/server": ^11.6.0
  tsdown:
    tsdown: ^0.15.5
  zod:
    zod: ^4.1.12
