import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { QueryProvider } from "@/providers/queryProvider";
import "./globals.css";

const interTight = Inter_Tight({
    variable: "--font-inter-tight",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${interTight.variable} antialiased`}>
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
}
