import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ModalProvider } from "@/providers/modalProvider";
import { QueryProvider } from "@/providers/queryProvider";
import "./globals.css";

const interTight = Inter_Tight({
    variable: "--font-inter-tight",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${interTight.variable} antialiased`}>
                <NuqsAdapter>
                    <QueryProvider>
                        <ModalProvider />
                        {children}
                    </QueryProvider>
                </NuqsAdapter>
            </body>
        </html>
    );
}
